*******************************************************************************
****** NANDX2 schematic NANDX2  <vs>  NANDX2 layout NANDX2
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45p1svt) MOS                                    2       4*
(g45n1svt) MOS                                    2       4*
                                             ------  ------
Total                                             4       8

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    2       4*          0       0
(g45p1svt) MOS                                    2       4*          0       0
(g45n1svt:SerMos2#1) MosBlk                       -       -           1       1
(g45p1svt:ParMos2#1) MosBlk                       -       -           1       1
                                             ------  ------      ------  ------
Total                                             4       8           2       2

Schematic and Layout Match
