*******************************************************************************
****** NANDX4 schematic NANDX4  <vs>  NANDX4 layout NANDX4
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45p1svt) MOS                                    2       8*
(g45n1svt) MOS                                    2       8*
                                             ------  ------
Total                                             4      16

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    2       8*          0       0
(g45p1svt) MOS                                    2       8*          0       0
(g45n1svt:SerMos2#1) MosBlk                       -       -           1       1
(g45p1svt:ParMos2#1) MosBlk                       -       -           1       1
                                             ------  ------      ------  ------
Total                                             4      16           2       2

Schematic and Layout Match
