*******************************************************************************
****** XNOR2X2 schematic XNOR2X2  <vs>  XNOR2X2 layout XNOR2X2
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45p1svt) MOS                                    7       8*
(g45n1svt) MOS                                    7       8*
                                             ------  ------
Total                                            14      16

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    7       8*          3       3
(g45p1svt) MOS                                    7       8*          3       3
(g45n1svt:SerMos2#1) MosBlk                       -       -           2       2
(g45p1svt:ParMos2#1) MosBlk                       -       -           2       2
(g45p1svt:SerMos4#1) MosBlk                       -       -           1       1
                                             ------  ------      ------  ------
Total                                            14      16          11      11

Schematic and Layout Match
