*******************************************************************************
****** XNOR3XL schematic XNOR3XL  <vs>  XNOR3XL layout XNOR3XL
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45n1svt) MOS                                   12      12
(g45p1svt) MOS                                   12      12
                                             ------  ------
Total                                            24      24

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                   12      12           4       4
(g45p1svt) MOS                                   12      12           4       4
(g45n1svt:SerMos2#1) MosBlk                       -       -           4       4
(g45p1svt:SerMos2#1) MosBlk                       -       -           4       4
                                             ------  ------      ------  ------
Total                                            24      24          16      16

Schematic and Layout Match
